### ISSUE TITLE
String [] do not work

### ISSUE THREAD

**Issue by cwolfinger** [romix/quickser#2] opened 2012-08-23 16:35 UTC
Hi - I have a list of String[] as a serialized field.  They serialize but they do not deserialize.  It seems like [] are not handled except for float, char, byte [], etc.

**Comment by romix** [comment] 2012-08-24 09:14
I tried with the following class:

class ClassWithListOfSringArrays implements Serializable {
    List<String[]> strList = new ArrayList<String[]>();
        ....
}

Is it something like what you describe? It seems to work for me without any problems. I guess I need more input from you to reproduce your problem

**Comment by romix** [comment] 2012-08-28 16:54
Seems to be fixed now.

**Closed as completed by romix** 2012-08-28 16:54 UTC
Labels: bug
