### ISSUE TITLE
Issue with Arrays and Class Type

### ISSUE THREAD

**Issue by cwolfinger** [romix/quickser#1] opened 2012-08-23 15:55 UTC
Hi - It appears that the serialization implementation makes an assumption that the component  type information is a concrete type.  As a result if you have an ArrayList<Object> or ArrayList<Serializable> then a null pointer exception is generated (definitely on the ArrayList<Serializable>.  It seems that each object in the array needs to be written out with it's own type field.

I did some more investigation and it seems like you may need to add !(obj instanceof Serializable) in the public void serialize(final DataOutput out, final Object obj,
            FastArrayList objectStack) throws IOException {

**Comment by romix** [comment] 2012-08-23 20:38
Will look into it tomorrow. Can you provide a small example/sketch of the code that fails? Also for the other bug you submitted as well. This would make it easier for me to fix it.

**Comment by romix** [comment] 2012-08-24 09:22
Based on your input I tried with the following class:

class ClassWithListOfLists implements Serializable {
        List<List<String>> listOfLists = new ArrayList<List<String>>();

```
    public ClassWithListOfLists(int len) {
        for(int i=0;i<len;++i) {
            ArrayList<String> subList = new ArrayList<String>();
            subList.add("Name");
            subList.add("elem" + i);
            listOfLists.add(subList);
        }
    }
```

}

Seems to work for me. Can you provide an example that would help me to reproduce your problem?

**Comment by cwolfinger** [comment] 2012-08-24 12:58
Hi yes will do that this morning

**Comment by cwolfinger** [comment] 2012-08-24 14:38
Below are 3 java class files and a sample main that demonstrate the issue:

``` java
package test.serialize;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import com.romix.quickser.Serialization;

public class TestAction implements Serializable {

    private static final long serialVersionUID = 2640786333075945218L;

    private transient String destinationName;
    private Map<String, List<Object[]>> parameters = new HashMap<String, List<Object[]>>();
    private List<Object> addedObjects = new ArrayList<Object>();
    private List<Object> removedObjects = new ArrayList<Object>();

    public String getDestinationName() {
        return destinationName;
    }

    public void setDestinationName(String destinationName) {
        this.destinationName = destinationName;
    }

    public void setParameter(String key, Serializable[] value) {
        List<Object[]> list = getParameters().get(key);
        if (list == null)
        {
            list = new ArrayList<Object[]>();
            getParameters().put(key, list);
        }
        list.add( value);
    }

    public List<Object[]> getParameter(String key) {
        return getParameters().get(key);
    }

    public List<Object> getAddedObjects() {
        return addedObjects;
    }
    public void setAddedObjects(List<Object> addedObjects) {
        this.addedObjects = addedObjects;
    }
    public List<Object> getRemovedObjects() {
        return removedObjects;
    }
    public void setRemovedObjects(List<Object> removedObjects) {
        this.removedObjects = removedObjects;
    }

    public Map<String, List<Object[]>> getParameters() {
        return parameters;
    }

    public void setParameters(Map<String, List<Object[]>> parameters) {
        this.parameters = parameters;
    }

    public static void main( String [] args) throws ClassNotFoundException, IOException
    {
        TestAction rar = new TestAction();
        rar.setDestinationName("abc");
        rar.setParameter("abc", new String[] {"abc123","efdrtf" });
        rar.setParameter("abc3", new String[] {"abc123","efdrtf" });
        TestNested1 message = new TestNested1();
        message.getPairs().put(UUID.randomUUID().toString(),
                new ArrayList<TestNested2>(
                        Collections.singletonList(new TestNested2(UUID.randomUUID().toString(), UUID.randomUUID().toString()))));
        message.getPairs().put(UUID.randomUUID().toString(),
                new ArrayList<TestNested2>(
                        Collections.singletonList(new TestNested2(UUID.randomUUID().toString(), UUID.randomUUID().toString()))));
        message.getPairs().put(UUID.randomUUID().toString(),
                new ArrayList<TestNested2>(
                        Collections.singletonList(new TestNested2(UUID.randomUUID().toString(), UUID.randomUUID().toString()))));
        message.getPairs().put(UUID.randomUUID().toString(),
                new ArrayList<TestNested2>(
                        Collections.singletonList(new TestNested2(UUID.randomUUID().toString(), UUID.randomUUID().toString()))));
        message.getPairs().put(UUID.randomUUID().toString(),
                new ArrayList<TestNested2>(
                        Collections.singletonList(new TestNested2(UUID.randomUUID().toString(), UUID.randomUUID().toString()))));
        message.getPairs().put(UUID.randomUUID().toString(),
                new ArrayList<TestNested2>(
                        Collections.singletonList(new TestNested2(UUID.randomUUID().toString(), UUID.randomUUID().toString()))));
        message.getPairs().put(UUID.randomUUID().toString(),
                new ArrayList<TestNested2>(
                        Collections.singletonList(new TestNested2(UUID.randomUUID().toString(), UUID.randomUUID().toString()))));
        message.getPairs().put(UUID.randomUUID().toString(),
                new ArrayList<TestNested2>(
                        Collections.singletonList(new TestNested2(UUID.randomUUID().toString(), UUID.randomUUID().toString()))));
        message.getPairs().put(UUID.randomUUID().toString(),
                new ArrayList<TestNested2>(
                        Collections.singletonList(new TestNested2(UUID.randomUUID().toString(), UUID.randomUUID().toString()))));
        message.getPairs().put(UUID.randomUUID().toString(),
                new ArrayList<TestNested2>(
                        Collections.singletonList(new TestNested2(UUID.randomUUID().toString(), UUID.randomUUID().toString()))));

        Serializable[] args2 = new Serializable[]{message};
        rar.setParameter("messsage", args2);

        long startTime = System.currentTimeMillis();
        int MAX = 300000;
        Serialization ser = new Serialization();
        for (int i = 0; i < MAX; i++)
        {
            ser.deserialize(ser.serialize(rar));
        }
        long endTime = System.currentTimeMillis();

        System.out.println("Speed = "+ ((endTime - startTime)*1.0));

    }

}

package test.serialize;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TestNested1 implements Serializable{

    /**
     * 
     */
    private static final long serialVersionUID = -9013973267486457642L;
    private Map<String,List<TestNested2>> pairs = new HashMap<String, List<TestNested2>>();

    public Map<String,List<TestNested2>> getPairs() {
        return pairs;
    }

    public void setPairs(Map<String,List<TestNested2>> pairs) {
        this.pairs = pairs;
    }

}


package test.serialize;

public class TestNested2 {


    public TestNested2() {

    }

    public TestNested2(String attr1, String attr2)
    {
        this.attr1 = attr1;
        this.attr2 = attr2;
    }

    public String getAttr1() {
        return attr1;
    }

    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }

    public String getAttr2() {
        return attr2;
    }

    public void setAttr2(String attr2) {
        this.attr2 = attr2;
    }

    private String attr1;

    private String attr2;
}
```

**Comment by romix** [comment] 2012-08-24 20:10
Thanks for providing a test for reproducing a problem. I fixed one NPE in Quickser code and I added Serializable interface for TestNested2. Now everything seems to work correctly on my side. 

I added your example to the set of test-cases. You can find it in the TestListOfObjects class. 

Please confirm if the problem was fixed also on your side.

**Comment by romix** [comment] 2012-08-28 12:22
Any feedback? Were you able to check if this fix works for you?

**Comment by cwolfinger** [comment] 2012-08-28 16:44
Hi - It seems to work now.

**Comment by romix** [comment] 2012-08-28 16:53
Good! Then I close this issue.

**Closed as completed by romix** 2012-08-28 16:53 UTC
Labels: bug
